### ISSUE TITLE
Error: Login failed!

### ISSUE THREAD

**Issue by skzidan** [Sergiy3013/genshin_automation#7]
Run node hoyolab.js
  node hoyolab.js
  shell: /usr/bin/bash -e {0}
  env:
    HOYOLAB_COOKIE: ***
    HOYOLAB_COOKIES: 
EXP Check in to the community:  HoYoLAB is currently carrying out server migration. This function is not available at the moment~
Error: Login failed! Please make sure the HOYOLAB_COOKIE value is correct!
Error: Process completed with exit code 1.

can you tell me which one to copy I copied ltoken and ltuid one . running only one account. 
![Ca2pture](https://user-images.githubusercontent.com/37244053/213197220-eac8c1f4-18dc-41f0-b812-06c9fe7ccd40.PNG)

**Comment by Sergiy3013** [comment]
You entered HOYOLAB_COOKIE incorrectly, read the instructions carefully
https://github.com/Sergiy3013/genshin_automation#2-set-up-variables-in-github
